# Generated by Django 4.0.4 on 2022-05-07 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActeDemander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActeFait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fm', models.TimeField()),
                ('To', models.TimeField()),
                ('description', models.TextField(max_length=500)),
                ('payed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cab_g.cabinet')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=25, unique=True)),
                ('img', models.ImageField(default='media/patient/default.png', upload_to='media/patient/')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Female', 'Femal'), ('Male', 'Male')], max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=25, unique=True)),
                ('address', models.CharField(max_length=500)),
                ('child', models.BooleanField(default=False)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cab_g.cabinet')),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PatientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cab_g.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('actedemander', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cab_g.actedemander')),
                ('actefait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cab_g.actefait')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cab_g.patient')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cab_g.cabinet')),
                ('medicament', models.ManyToManyField(to='cab_g.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('payed', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cab_g.appointment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='media/doctor/default.png', upload_to='media/doctor/')),
                ('inp', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Female', 'Femal'), ('Male', 'Male')], max_length=255)),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cab_g.cabinet')),
                ('specialiste', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cab_g.specialite')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='media/assistant/default.png', upload_to='media/assistant/')),
                ('cin', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('gender', models.CharField(choices=[('Female', 'Femal'), ('Male', 'Male')], max_length=255)),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cab_g.cabinet')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cab_g.patient'),
        ),
        migrations.AddField(
            model_name='actefait',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cab_g.cabinet'),
        ),
        migrations.AddField(
            model_name='actedemander',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cab_g.cabinet'),
        ),
    ]
